-- RETIRED 2026-09-08. sales_ops.order_customer is no longer built by its own scheduled query.
-- It is section 1 (ORDER_CUSTOMER, then order_sequence) of sql/sales_ops.order_marts.sql, deployed as ONE scheduled query.
-- Edit and deploy that file. Standalone history: git log -- sql/sales_ops.order_customer.sql
